version: '3'

services:
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-persistence:/bitnami

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234567890
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb:
